kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-deployment
  labels:
    app.kubernetes.io/part-of: gdx-agreements-tracker
    app.kubernetes.io/component: backend
    app.openshift.io/connects-to: coreDB
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      labels:
        connection: net-database-client
    spec:
      containers:
        - name: api
          image: bcgovgdx/gdx-agreements-tracker-api-run
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POSTGRES_DB
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: secrets
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: "300m"
              memory: 200Mi
